### PR TITLE
add tentative outline to README

### PR DESCRIPTION
**Pull request by boshek**
A tentative outline, focussed at this point squarely on topics.

### CODE REVIEW

**Comment by ateucher** [comment]
One question before we get too far. Do we want to continue to update this repo, or create a new 2-day version so we don't lose this? (NB. I know with git we technically don't lose it, but functionally we kind of would)

**Comment by gcperk** [comment]
I would opt for separate repo.

**Comment by boshek** [comment]
My thought is - if after this one we this 1-day course, we would end up taking updated materials from this repo anyways then if you did another 2 day course after that we'd draw from the updated 1 day course as well. The two repos would inextricably be linked (unless they remained static) so I wonder if releases in the same repo might function in the same way? A separate two day course repo would probably be ideal from a user perspective but it just means a little more work in maintenance.

**Comment by ateucher** [comment]
True, though I think it might be good to have a 1-day repo and 2-day repo... then do releases for each one taught?

**Comment by boshek** [comment]
Fine by me

**Comment by stephhazlitt** [comment]
I also lean to one repo with iterative improvements. Is there a way to design the repo to accommodate flexibility in length? e.g. denote which lesson(s) would only be covered in a 2-day course?

**Comment by boshek** [comment]
Should probably get some consensus here. How about one repo with a directory for 1 day course and a directory for a 2 day course?

**Comment by gcperk** [comment]
I'm happy to go with one repo as you have a good point about updates. I'm curious to see how to designate day 1 from day 2.

**Comment by ateucher** [comment]
@boshek do you want to restructure this PR or should we merge then create the two directories?

**Comment by boshek** [comment]
@ateucher I will do that. I think it'll likely break the bookdown.

**Comment by ateucher** [comment]
Permanently? i.e. 1 repo = 1 bookdown? Or we can fix it after?

**Comment by boshek** [comment]
Oh no I think we can definitely sub folders to create a bookdown and have the highest heading level be 1-day and 2-day. It'll just take some work so it'll temporarily be down.

**Comment by stephhazlitt** [comment]
OK, 2-day repo started [here](https://github.com/bcgov/ds-intro-to-r-2-day) &mdash; looking forward to the git-foo to shift this PR over 😄

**Comment by boshek** [comment]
All material migrated over here: https://github.com/bcgov/ds-intro-to-r-2-day.

**Pull request closed without merging**
